# Generated by Django 3.0.5 on 2020-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_simple_question_txt_de', models.CharField(max_length=30)),
                ('menu_simple_question_txt_pl', models.CharField(max_length=30)),
                ('menu_full_test_txt_de', models.CharField(max_length=30)),
                ('menu_full_test_txt_pl', models.CharField(max_length=30)),
                ('menu_fischerschein_info_txt_de', models.CharField(max_length=30)),
                ('menu_fischerschein_info_txt_pl', models.CharField(max_length=30)),
                ('menu_FAQ_txt_de', models.CharField(max_length=30)),
                ('menu_FAQ_txt_pl', models.CharField(max_length=30)),
                ('menu_about_project_de', models.CharField(max_length=30)),
                ('menu_about_project_pl', models.CharField(max_length=30)),
                ('hero_main_txt_de', models.CharField(max_length=80)),
                ('hero_main_txt_pl', models.CharField(max_length=80)),
                ('hero_under_txt_de', models.CharField(max_length=80)),
                ('hero_under_txt_pl', models.CharField(max_length=80)),
            ],
        ),
    ]
