# Generated by Django 3.0.5 on 2020-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPageTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_page_new_test_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_new_test_btn_txt_pl', models.CharField(max_length=30)),
                ('test_page_check_test_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_check_test_btn_txt_pl', models.CharField(max_length=30)),
                ('test_page_test_info_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_test_info_btn_txt_pl', models.CharField(max_length=30)),
                ('test_page_other_question_txt_pl', models.CharField(max_length=80)),
                ('test_page_ichtyology_btn_txt_de', models.CharField(max_length=50)),
                ('test_page_ichtyology_btn_txt_pl', models.CharField(max_length=50)),
                ('test_page_maintenace_of_fish_water_btn_txt_de', models.CharField(max_length=50)),
                ('test_page_maintenace_of_fish_water_btn_txt_pl', models.CharField(max_length=50)),
                ('test_page_fishing_gear_btn_txt_de', models.CharField(max_length=50)),
                ('test_page_fishing_gear_btn_txt_pl', models.CharField(max_length=50)),
                ('test_page_treatment_of_cathing_fish_btn_txt_de', models.CharField(max_length=50)),
                ('test_page_treatment_of_cathing_fish_btn_txt_pl', models.CharField(max_length=50)),
                ('test_page_relevant_legislation_btn_txt_de', models.CharField(max_length=50)),
                ('test_page_relevant_legislation_btn_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_results_title_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_modal_results_correct_answer_txt_de', models.CharField(max_length=30)),
                ('test_page_modal_results_correct_answer_txt_pl', models.CharField(max_length=30)),
                ('test_page_modal_ichtyology_txt_de', models.CharField(max_length=50)),
                ('test_page_modal_ichtyology_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_maintenace_of_fish_water_txt_de', models.CharField(max_length=50)),
                ('test_page_modal_maintenace_of_fish_water_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_fishing_gear_txt_de', models.CharField(max_length=50)),
                ('test_page_modal_fishing_gear_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_treatment_of_cathing_fish_txt_de', models.CharField(max_length=50)),
                ('test_page_modal_treatment_of_cathing_fish_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_relevant_legislation_txt_de', models.CharField(max_length=50)),
                ('test_page_modal_relevant_legislation_txt_pl', models.CharField(max_length=50)),
                ('test_page_modal_try_again_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_modal_try_again_btn_txt_pl', models.CharField(max_length=30)),
                ('test_page_modal_new_test_btn_txt_de', models.CharField(max_length=30)),
                ('test_page_modal_new_test_btn_txt_pl', models.CharField(max_length=30)),
            ],
        ),
    ]
