# Generated by Django 3.0.5 on 2020-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_testpagetxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_results_title_btn_txt_pl',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_close_btn_txt_de',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_close_btn_txt_pl',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_text_txt_de',
            field=models.CharField(default='empty', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_text_txt_pl',
            field=models.CharField(default='empty', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_title_txt_de',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_modal_test_info_title_txt_pl',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpagetxt',
            name='test_page_other_question_txt_de',
            field=models.CharField(default='empty', max_length=80),
            preserve_default=False,
        ),
    ]
